/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as AnniversairesRouteImport } from './routes/anniversaires'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FamilleRouteImport } from './routes/famille'
import { Route as InfosRouteImport } from './routes/infos'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PlanningsRouteImport } from './routes/plannings'
import { Route as TachesRouteImport } from './routes/taches'
import { Route as MembreMemberIdRouteImport } from './routes/membre.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesRoute = ActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => rootRouteImport,
} as any)
const AnniversairesRoute = AnniversairesRouteImport.update({
  id: '/anniversaires',
  path: '/anniversaires',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilleRoute = FamilleRouteImport.update({
  id: '/famille',
  path: '/famille',
  getParentRoute: () => rootRouteImport,
} as any)
const InfosRoute = InfosRouteImport.update({
  id: '/infos',
  path: '/infos',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningsRoute = PlanningsRouteImport.update({
  id: '/plannings',
  path: '/plannings',
  getParentRoute: () => rootRouteImport,
} as any)
const TachesRoute = TachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => rootRouteImport,
} as any)
const MembreMemberIdRoute = MembreMemberIdRouteImport.update({
  id: '/membre/$memberId',
  path: '/membre/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/anniversaires': typeof AnniversairesRoute
  '/calendrier': typeof CalendrierRoute
  '/documents': typeof DocumentsRoute
  '/famille': typeof FamilleRoute
  '/infos': typeof InfosRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
  '/plannings': typeof PlanningsRoute
  '/taches': typeof TachesRoute
  '/membre/$memberId': typeof MembreMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/anniversaires': typeof AnniversairesRoute
  '/calendrier': typeof CalendrierRoute
  '/documents': typeof DocumentsRoute
  '/famille': typeof FamilleRoute
  '/infos': typeof InfosRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
  '/plannings': typeof PlanningsRoute
  '/taches': typeof TachesRoute
  '/membre/$memberId': typeof MembreMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/anniversaires': typeof AnniversairesRoute
  '/calendrier': typeof CalendrierRoute
  '/documents': typeof DocumentsRoute
  '/famille': typeof FamilleRoute
  '/infos': typeof InfosRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
  '/plannings': typeof PlanningsRoute
  '/taches': typeof TachesRoute
  '/membre/$memberId': typeof MembreMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activites'
    | '/anniversaires'
    | '/calendrier'
    | '/documents'
    | '/famille'
    | '/infos'
    | '/notes'
    | '/parametres'
    | '/plannings'
    | '/taches'
    | '/membre/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activites'
    | '/anniversaires'
    | '/calendrier'
    | '/documents'
    | '/famille'
    | '/infos'
    | '/notes'
    | '/parametres'
    | '/plannings'
    | '/taches'
    | '/membre/$memberId'
  id:
    | '__root__'
    | '/'
    | '/activites'
    | '/anniversaires'
    | '/calendrier'
    | '/documents'
    | '/famille'
    | '/infos'
    | '/notes'
    | '/parametres'
    | '/plannings'
    | '/taches'
    | '/membre/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitesRoute: typeof ActivitesRoute
  AnniversairesRoute: typeof AnniversairesRoute
  CalendrierRoute: typeof CalendrierRoute
  DocumentsRoute: typeof DocumentsRoute
  FamilleRoute: typeof FamilleRoute
  InfosRoute: typeof InfosRoute
  NotesRoute: typeof NotesRoute
  ParametresRoute: typeof ParametresRoute
  PlanningsRoute: typeof PlanningsRoute
  TachesRoute: typeof TachesRoute
  MembreMemberIdRoute: typeof MembreMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites': {
      id: '/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anniversaires': {
      id: '/anniversaires'
      path: '/anniversaires'
      fullPath: '/anniversaires'
      preLoaderRoute: typeof AnniversairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/famille': {
      id: '/famille'
      path: '/famille'
      fullPath: '/famille'
      preLoaderRoute: typeof FamilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infos': {
      id: '/infos'
      path: '/infos'
      fullPath: '/infos'
      preLoaderRoute: typeof InfosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plannings': {
      id: '/plannings'
      path: '/plannings'
      fullPath: '/plannings'
      preLoaderRoute: typeof PlanningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taches': {
      id: '/taches'
      path: '/taches'
      fullPath: '/taches'
      preLoaderRoute: typeof TachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membre/$memberId': {
      id: '/membre/$memberId'
      path: '/membre/$memberId'
      fullPath: '/membre/$memberId'
      preLoaderRoute: typeof MembreMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitesRoute: ActivitesRoute,
  AnniversairesRoute: AnniversairesRoute,
  CalendrierRoute: CalendrierRoute,
  DocumentsRoute: DocumentsRoute,
  FamilleRoute: FamilleRoute,
  InfosRoute: InfosRoute,
  NotesRoute: NotesRoute,
  ParametresRoute: ParametresRoute,
  PlanningsRoute: PlanningsRoute,
  TachesRoute: TachesRoute,
  MembreMemberIdRoute: MembreMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
